---
title: "NIHR Health Informatics Collaborative - Critical Care"
date: "2022-11-16"
draft: false
description: "Real world data from NHS Critical Care Units"
author: "Steve Harris"
date: 2022-11-16
toc: false
categories: 
  - datasets 
  - CCHIC
  - NHS
---

Since 2014 data from the critical care units at Cambridge, Guys/Kings/St Thomas', Imperial, Oxford, and University College London has been extracted and stored securely in a standardised format.

These data are crucially needed by healthcare professionals for the delivery and continuity of care; by administrators for audit, planning and service improvement; and by academic and industry researchers for the translation of scientific progress into patient benefit. Through this process, CC-HIC can improve patient outcomes, reduce the costs of care, and accelerate the pace of translational health research.

The physical database is held at the UCL IDHS within the Information Services Division of University College London (UCL). UCL manage and ensure that the database and the surrounding governance structures are appropriate for holding identifiable and sensitive NHS data. The safe haven is compliant to NHS Information Governance Toolkit Level 2 and operates to the ISO 27001, the Safe Haven already holds identifiable, sensitive NHS data for secondary purpose. The Critical Care HIC management group will maintain oversight and be the point of contact for researchers wishing to access data.

The original data specification and tooling has now been archived but can be reviewed [here](https://github.com/ropensci-archive/cleanEHR/blob/master/README-not.md). The latest documentation is now [here](https://uclh-criu.github.io/hic-alchemist-docs/). The latest version has moved to the OMOP Common Data Model.