---
title: "Faster, Better Blink Detection through Curriculum Learning by Augmentation"
type: "article"
author: "Al-Hindawi A, Vizcaychipi M, Demiris Y"
year: "2022"
publication: "ETRA"
# preprint: "https://psyarxiv.com/futv2/"
doi: "https://doi.org/10.1145/3517031.3529617"
# materials: "https://osf.io/gewrp/"
toc: false
categories:
  - eye tracking
  - blink detection
---

## Citation (APA 7)

> Al-Hindawi, A., Vizcaychipi, M., & Demiris, Y. (2022, June). Faster, Better Blink Detection through Curriculum Learning by Augmentation. In 2022 Symposium on Eye Tracking Research and Applications.
 
## Abstract

Blinking is a useful biological signal that can gate gaze regression models to avoid the use of incorrect data in downstream tasks. Existing datasets are imbalanced both in frequency of class but also in intra-class difficulty which we demonstrate is a barrier for curriculum learning. We thus propose a novel curriculum augmentation scheme that aims to address frequency and difficulty imbalances implicitly which are are terming Curriculum Learning by Augmentation (CLbA).

Using Curriculum Learning by Augmentation (CLbA), we achieve a state-of-the-art performance of mean Average Precision (mAP) 0.971 using ResNet-18 up from the previous state-of-the-art of mean Average Precision (mAP) of 0.757 using DenseNet-121 whilst outcompeting Curriculum Learning by Bootstrapping (CLbB) by a significant margin with improved calibration. This new training scheme thus allows the use of smaller and more performant Convolutional Neural Network (CNN) backbones fulfilling Nyquist criteria to achieve a sampling frequency of 102.3Hz. This paves the way for inference of blinking in real-time applications.

