---
title: "Vaccinating adolescents against SARS-CoV-2 in England: a risk–benefit analysis"
type: "article"
author: "Gurdasani D, Bhatt S, Costello A, Denaxas S, Flaxman S, Greenhalgh T, Griffin S, Hyde Z, Katzourakis A, McKee M, Michie S, Ratmann O, Reicher S, Scally G, admin, Yates C, Ziauddeen H & Pagel C"
year: "2021"
publication: "Journal of the Royal Society of Medicine"
# preprint: "https://psyarxiv.com/futv2/"
doi: "10.1177/01410768211052589"
# materials: "https://osf.io/gewrp/"
toc: false
categories:
  - COVID-19
  - EHR
  - epidemiology
  - vaccination
  - paediatrics
  - HDR UK
  - BHF Data Science Centre
---

## Citation

> Gurdasani, D., Bhatt, S., Costello, A., Denaxas, S., Flaxman, S., Greenhalgh, T., Griffin, S., Hyde, Z., Katzourakis, A., McKee, M., Michie, S., Ratmann, O., Reicher, S., Scally, G., Tomlinson, C., Yates, C., Ziauddeen, H., & Pagel, C. (2021). Vaccinating adolescents against SARS-CoV-2 in England: A risk–benefit analysis. Journal of the Royal Society of Medicine, 114(11), 513–524. https://doi.org/10.1177/01410768211052589




 
## Abstract

Objective  
To offer a quantitative risk–benefit analysis of two doses of SARS-CoV-2 vaccination among adolescents in England.  
Design  
Following the risk–benefit analysis methodology carried out by the US Centers for Disease Control, we calculated historical rates of hospital admission, Intensive Care Unit admission and death for ascertained SARS-CoV-2 cases in children aged 12–17 in England. We then used these rates alongside a range of estimates for incidence of long COVID, vaccine efficacy and vaccine-induced myocarditis, to estimate hospital and Intensive Care Unit admissions, deaths and cases of long COVID over a period of 16 weeks under assumptions of high and low case incidence.  
Participants  
All 12–17 year olds with a record of confirmed SARS-CoV-2 infection in England between 1 July 2020 and 31 March 2021 using national linked electronic health records, accessed through the British Heart Foundation Data Science Centre.  
Main outcome measures  
Hospitalisations, Intensive Care Unit admissions, deaths and cases of long COVID averted by vaccinating all 12–17 year olds in England over a 16-week period under different estimates of future case incidence.  
Results  
At high future case incidence of 1000/100,000 population/week over 16 weeks, vaccination could avert 4430 hospital admissions and 36 deaths over 16 weeks. At the low incidence of 50/100,000/week, vaccination could avert 70 hospital admissions and two deaths over 16 weeks. The benefit of vaccination in terms of hospitalisations in adolescents outweighs risks unless case rates are sustainably very low (below 30/100,000 teenagers/week). Benefit of vaccination exists at any case rate for the outcomes of death and long COVID, since neither have been associated with vaccination to date.  
Conclusions  
Given the current (as at 15 September 2021) high case rates (680/100,000 population/week in 10–19 year olds) in England, our findings support vaccination of adolescents against SARS-CoV2.  