---
title: "Can network science reveal structure in a complex healthcare system? A network analysis using data from emergency surgical services"
type: "article"
author: "Katharina Kohler, Phyu Phyu Nwe Myint, Sein Wynn, Alexander Komashie, Robyn Winters, Myat Thu, Mu Mu Naing, Thinn Hlaing, Rowan Burnstein, Zaw Wai Soe, John Clarkson, David Menon, Peter John Hutchinson, Tom Bashford "
year: "2022"
publication: "BMJ Open"

doi: "https://bmjopen.bmj.com/content/12/5/e059935"

toc: false
categories:
  - health systems
  - peri-operative care
  - global health
  - journal article
---

## Citation (APA 7)

> Kohler K, Nwe Myint PP, Wynn S, et alSystems approach to improving traumatic brain injury care in Myanmar: a mixed-methods study from lived experience to discrete event simulation BMJ Open 2022;12:e059935. doi: 10.1136/bmjopen-2021-059935
 
## Abstract

Abstract: Objectives Traumatic brain injury (TBI) is a global health problem, whose management in low-resource settings is hampered by fragile health systems and lack of access to specialist services. Improvement is complex, given the interaction of multiple people, processes and institutions. We aimed to develop a mixed-method approach to understand the TBI pathway based on the lived experience of local people, supported by quantitative methodologies and to determine potential improvement targets.

Design: We describe a systems approach based on narrative exploration, participatory diagramming, data collection and discrete event simulation (DES), conducted by an international research collaborative.

Setting: The study is set in the tertiary neurotrauma centre in Yangon General Hospital, Myanmar, in 2019–2020 (prior to the SARS-CoV2 pandemic).

Participants: The qualitative work involved 40 workshop participants and 64 interviewees to explore the views of a wide range of stakeholders including staff, patients and relatives. The 1-month retrospective admission snapshot covered 85 surgical neurotrauma admissions.

Results: The TBI pathway was outlined, with system boundaries defined around the management of TBI once admitted to the neurosurgical unit. Retrospective data showed 18% mortality, 71% discharge to home and an 11% referral rate. DES was used to investigate the system, showing its vulnerability to small surges in patient numbers, with critical points being CT scanning and observation ward beds. This explorative model indicated that a modest expansion of observation ward beds to 30 would remove the flow-limitations and indicated possible consequences of changes.

Conclusions: A systems approach to improving TBI care in resource-poor settings may be supported by simulation and informed by qualitative work to ground it in the direct experience of those involved. Narrative interviews, participatory diagramming and DES represent one possible suite of methods deliverable within an international partnership. Findings can support targeted improvement investments despite coexisting resource limitations while indicating concomitant risks.
---
