---
title: "COVID-19 trajectories among 57 million adults in England: a cohort study using electronic health records"
type: "article"
author: "Johan H Thygesen, Chris Tomlinson, Sam Hollings, Mehrdad Mizani, Alex Handy, Ashley Akbari, Amitava Banerjee, Jennifer Cooper, Alvina Lai, Ken Li, Bilal Mateen, Naveed Sattar, Reecha Sofat, Ana Torralbo, Honghan Wu, Angela Wood, Jonathan A C Sterne, Christina Pagel, William Whiteley, Cathie Sudlow, Harry Hemingway, Spiros Denaxas, on behalf of the CVD-COVID-UK Consortium"
year: "2022"
publication: "Lancet Digital Health"
# preprint: "https://psyarxiv.com/futv2/"
doi: "10.1016/S2589-7500(22)00091-7"
# materials: "https://osf.io/gewrp/"
toc: false
categories:
  - COVID-19
  - EHR
  - phenomics
  - epidemiology
  - linkage
  - HDR UK
  - BHF Data Science Centre
---

## Citation (APA 7)

> Thygesen, J. H., Tomlinson, C., Hollings, S., Mizani, M. A., Handy, A., Akbari, A., Banerjee, A., Cooper, J., Lai, A. G., Li, K., Mateen, B. A., Sattar, N., Sofat, R., Torralbo, A., Wu, H., Wood, A., Sterne, J. A. C., Pagel, C., Whiteley, W. N., … Zuccolo, L. (2022). COVID-19 trajectories among 57 million adults in England: A cohort study using electronic health records. The Lancet Digital Health, 4(7), e542–e557. https://doi.org/10.1016/S2589-7500(22)00091-7

 
## Abstract

Background  
Updatable estimates of COVID-19 onset, progression, and trajectories underpin pandemic mitigation efforts. To identify and characterise disease trajectories, we aimed to define and validate ten COVID-19 phenotypes from nationwide linked electronic health records (EHR) using an extensible framework.  
Methods  
In this cohort study, we used eight linked National Health Service (NHS) datasets for people in England alive on Jan 23, 2020. Data on COVID-19 testing, vaccination, primary and secondary care records, and death registrations were collected until Nov 30, 2021. We defined ten COVID-19 phenotypes reflecting clinically relevant stages of disease severity and encompassing five categories: positive SARS-CoV-2 test, primary care diagnosis, hospital admission, ventilation modality (four phenotypes), and death (three phenotypes). We constructed patient trajectories illustrating transition frequency and duration between phenotypes. Analyses were stratified by pandemic waves and vaccination status.
Findings  
Among 57 032 174 individuals included in the cohort, 13 990 423 COVID-19 events were identified in 7 244 925 individuals, equating to an infection rate of 12·7% during the study period. Of 7 244 925 individuals, 460 737 (6·4%) were admitted to hospital and 158 020 (2·2%) died. Of 460 737 individuals who were admitted to hospital, 48 847 (10·6%) were admitted to the intensive care unit (ICU), 69 090 (15·0%) received non-invasive ventilation, and 25 928 (5·6%) received invasive ventilation. Among 384 135 patients who were admitted to hospital but did not require ventilation, mortality was higher in wave 1 (23 485 [30·4%] of 77 202 patients) than wave 2 (44 220 [23·1%] of 191 528 patients), but remained unchanged for patients admitted to the ICU. Mortality was highest among patients who received ventilatory support outside of the ICU in wave 1 (2569 [50·7%] of 5063 patients). 15 486 (9·8%) of 158 020 COVID-19-related deaths occurred within 28 days of the first COVID-19 event without a COVID-19 diagnoses on the death certificate. 10 884 (6·9%) of 158 020 deaths were identified exclusively from mortality data with no previous COVID-19 phenotype recorded. We observed longer patient trajectories in wave 2 than wave 1.
Interpretation  
Our analyses illustrate the wide spectrum of disease trajectories as shown by differences in incidence, survival, and clinical pathways. We have provided a modular analytical framework that can be used to monitor the impact of the pandemic and generate evidence of clinical and policy relevance using multiple EHR sources.
Funding  
British Heart Foundation Data Science Centre, led by Health Data Research UK.


