---
title: "Data Clinic"
description: "An introduction to the data clinic"
author: "Ruaraidh Campbell"
date: 2022-11-16
toc: true
categories: 
     - Data Clinic
     - Noobie
     - UCLH
--- 

# What is the 'Data Clinic'? 

The Data Clinic is a Quality Improvement initiative to help frontline healthcare workers (e.g. doctors, nursing staff, allied health professionals, etc) in Critical Care get data from EPIC.  

This is to improve the ease and speed of audits, QIPs and service evaluations we perform in Critical Care. 

# What are the issues that the Data Clinic is trying to solve? 

UCLH has invested millons of pounds to obtain an fully electronic health record system (EHRS) in the form of EPIC since 2019. It aims to be a leader in the field of technologically-enabled healthcare.

The previous method for obtaining data from EPIC was through contacting the Business Intelligence (BI) team, whose role it is to monitor performance data in the Critical Care department and service data requests. However this had a number of issues: 

     - Many clinical staff are unaware of who the BI team are or what they do 
     - The process of requesting data often took the form of numerous back-and-forth emails between clinical staff and the BI team, clarifying what data is required vs what is possible to extract. This process was often time-consuming and frustrating for both the clinical staff and BI team. 
     - Although the BI team have a good understanding of how to find data in Epic and manage it, sometimes they lack the clinical understanding and direction to provide learning from it. 

The Data Clinic aims to improve the process of providing data to clinical staff using two approaches:

     1. We aim to understand the clinical question the requestor is trying to answer and, with our knowledge of the data that is available, clarify exactly what data is required for their project.
     2. Then we work with the BI team to provide that data for the requestor as quickly as possible, in the form that the requestor needs.

We hypothesise that this shall benefit both clinical staff and the BI team. 

     Clinical staff: 
     - makes the process of getting data from EPIC clearer
     - enhances understanding of the data that is available from EPIC 
     - help with analysis of data (if required)
     - easier to get the data needed to complete audit/QIP/service evaluations (thereby increasing the number of projects completed and improving patient care)

     BI team:
     - Saves time/frustration emailing back-and-forth with clinical staff   
     - Better understanding of clinical relevance of their work (through feedback on the results of QI projects)

# How does the Data Clinic work? 

After we recieve your request, a member of our team will contact you to arrange a meeting to discuss your project and the data you require (+/- any statistical help required).   

Following this meeting, we shall extract a 1st draft of the data with the BI team.  

We shall then arrange a second meeting with you to show you the data. If you are happy, we shall then extract the full dataset you need. If you are not satisfied, we shall arrange further extractions and meetings until the data fits your requirements. 

The length of this process can be variable, but we aim to deliver at least the 1st extract of the data within 1 month. 

We try to be flexible with arranging meetings as we realise you are busy! 

# How do I access the Data Clinic? 

There are 2 main ways of contacting the Data Clinic, depending on the nature of your request. 

If you are doing an Audit/QI project that requires EPIC data, please register your project with the Audit/QI team. A member of the team will then get in contact with you to discuss your project. When the time is right, they will then pass your details on to the Data Clinic, when we shall then get in touch! 

If your project is not Audit/QI, please email us at: uclh.critical.data@nhs.net

For any other questions/requests, please feel free to drop us an email or speak to any of the Data Fellows or Tim Bonicci in person! 

# Relevant contacts 

Dr Tim Bonnici: Data Lead for Critical Care (t.bonnici@nhs.net)    

Data Fellows: Change yearly, the fellows for 2022/23 are listed below  

- Dr Ruaraidh Campbell (ruaraidh.campbell@nhs.net)
- Dr Sarah Vaughan (s.vaughan5@nhs.net)
- Dr Hrisheekesh Vaidya (h.vaidya@nhs.net)
