---
title: "Digital ethnicity data in population-wide electronic health records in England: a description of completeness, coverage, and granularity of diversity"
type: "preprint"
author: "Marta Pineda-Moncusí, Freya Allery, Antonella Delmestri, Thomas Bolton, John Nolan, Johan Thygesen, Alex Handy, Amitava Banerjee, Spiros Denaxas, Christopher Tomlinson, Alastair K Denniston, Cathie Sudlow, Ashley Akbari, Angela Wood, Gary S Collins, Irene Petersen, Kamlesh Khunti, Daniel Prieto-Alhambra, Sara Khalid, on behalf of the CVD-COVID-UK Consortium"
year: "2022"
publication: "medRxiv"
# preprint: "https://psyarxiv.com/futv2/"
doi: "10.1101/2022.11.11.22282217"
# materials: "https://osf.io/gewrp/"
toc: false
categories:
  - COVID-19
  - EHR
  - linkage
  - ethnicity
  - diversity
  - fairness
  - HDR UK
  - BHF Data Science Centre
---

## Citation

> Digital ethnicity data in population-wide electronic health records in England: a description of completeness, coverage, and granularity of diversity
Marta Pineda-Moncusí, Freya Allery, Antonella Delmestri, Thomas Bolton, John Nolan, Johan Thygesen, Alex Handy, Amitava Banerjee, Spiros Denaxas, Christopher Tomlinson, Alastair K Denniston, Cathie Sudlow, Ashley Akbari, Angela Wood, Gary S Collins, Irene Petersen, Kamlesh Khunti, Daniel Prieto-Alhambra, Sara Khalid
medRxiv 2022.11.11.22282217; doi: https://doi.org/10.1101/2022.11.11.22282217

 
## Abstract

Background  
The link between ethnicity and healthcare inequity, and the urgency for better data is well-recognised. This study describes ethnicity data in nation-wide electronic health records in England, UK.  

Methods  
We conducted a retrospective cohort study using de-identified person-level records for the England population available in the National Health Service (NHS) Digital trusted research environment. Primary care records (GDPPR) were linked to hospital and national mortality records. We assessed completeness, consistency, and granularity of ethnicity records using all available SNOMED-CT concepts for ethnicity and NHS ethnicity categories.  

Findings  
From 61.8 million individuals registered with a primary care practice in England, 51.5 (83.3%) had at least one ethnicity record in GDPPR, increasing to 93·9% when linked with hospital records. Approximately 12·0% had at least two conflicting ethnicity codes in primary care records. Women were more likely to have ethnicity recorded than men. Ethnicity was missing most frequently in individuals from 18 to 39 years old and in the southern regions of England. Individuals with an ethnicity record had more comorbidities recorded than those without. Of 489 SNOMED-CT ethnicity concepts available, 255 were used in primary care records. Discrepancies between SNOMED-CT and NHS ethnicity categories were observed, specifically within “Other-” ethnicity groups.  

Interpretation  
More than 250 ethnicity sub-groups may be found in health records for the English population, although commonly categorised into “White”, “Black”, “Asian”, “Mixed”, and “Other”. One in ten individuals do not have ethnicity information recorded in primary care or hospital records. SNOMED-CT codes represent more diversity in ethnicity groups than the NHS ethnicity classification. Improved recording of self-reported ethnicity at first point-of-care and consistency in ethnicity classification across healthcare settings can potentially improve the accuracy of ethnicity in research and ultimately care for all ethnicities.  

Funding  
British Heart Foundation Data Science Centre led by Health Data Research UK.


